version: "3"
services:
  ldap:
    healthcheck:
      test: nc -z localhost 2812 || exit 1
      interval: 60s
      timeout: 10s
      retries: 10
    hostname: ldap.mail.local
    image: carbonio/ce-ldap-u20:latest
    ports:
      - "389:389"
  db:
    image: carbonio-db
    restart: always
    environment:
      MARIADB_USER: zextras
      MARIADB_PASSWORD: zextras
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "7306:3306"
