# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: attrs.xml
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-yaml
        - id: check-added-large-files
        - id: check-toml
        - id: mixed-line-ending
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: shellcheck
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: pretty-format-java
        args: [--autofix]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.31.1
    hooks:
      - id: markdownlint
      - id: markdownlint-fix
  - repo: https://github.com/jorisroovers/gitlint
    rev:  v0.17.0
    hooks:
      - id: gitlint
