services:
  app:
    build: .
    depends_on:
      ldap:
        condition: service_healthy
    ports:
      - "7070:7070"
      - "7071:7071"
    volumes:
      - "./:/app"
      - "~/.m2:/root/.m2"
  ldap:
    image: carbonio/ce-ldap-u20
    hostname: ldap.mail.local
    healthcheck:
      test: nc -z localhost 2812 || exit 1 # check monit up and running
    ports:
      - "389:389"
    volumes:
      - "./store/build/ldap:/opt/zextras/common/etc/openldap/zimbra"
      - "./entrypoint-ldap.sh:/entrypoint-ldap.sh"
    entrypoint: ["/entrypoint-ldap.sh"]
