#!/usr/bin/bash

/opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /opt/zextras/common/etc/openldap/zimbra/carbonio.ldif
/opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /opt/zextras/common/etc/openldap/zimbra/zimbra_globalconfig.ldif
/opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /opt/zextras/common/etc/openldap/zimbra/zimbra_defaultcos.ldif
/opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /opt/zextras/common/etc/openldap/zimbra/zimbra_defaultexternalcos.ldif
/opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /opt/zextras/common/etc/openldap/zimbra/mimehandlers.ldif

# Replace SMTP config
cat <<EOF > /tmp/replace_smtp_host.ldif
dn: cn=config,cn=zimbra
changetype: modify
replace: zimbraSmtpHostname
zimbraSmtpHostname: postfix
-
replace: zimbraCsrfRefererCheckEnabled
zimbraCsrfRefererCheckEnabled: FALSE
-
replace: zimbraMailMode
zimbraMailMode: http
-
replace: zimbraMailPort
zimbraMailPort: 8080
-
replace: zimbraMailSSLPort
zimbraMailSSLPort: 8443
-
replace: zimbraImapBindPort
zimbraImapBindPort: 7143
-
replace: zimbraImapSSLBindPort
zimbraImapSSLBindPort: 7993
EOF

cat <<EOF > /tmp/replace_smtp_port.ldif
dn: cn=config,cn=zimbra
changetype: modify
replace: zimbraSmtpPort
zimbraSmtpPort: 25
EOF

/opt/zextras/common/bin/ldapmodify -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /tmp/replace_smtp_host.ldif
/opt/zextras/common/bin/ldapmodify -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /tmp/replace_smtp_port.ldif

SSHA_ROOT_PASSWORD=$(/opt/zextras/common/sbin/slappasswd -s "${LDAP_ROOT_PASSWORD}")
cat <<EOF > /tmp/replace_postfix_password.ldif
dn: uid=zmpostfix,cn=appaccts,cn=zimbra
changetype: modify
replace: userPassword
userPassword: ${SSHA_ROOT_PASSWORD}
EOF
/opt/zextras/common/bin/ldapmodify -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /tmp/replace_postfix_password.ldif

cat <<EOF > /tmp/replace_nginx_password.ldif
dn: uid=zmnginx,cn=appaccts,cn=zimbra
changetype: modify
replace: userPassword
userPassword: ${SSHA_ROOT_PASSWORD}
EOF
/opt/zextras/common/bin/ldapmodify -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /tmp/replace_nginx_password.ldif

SSHA_ADMIN_PASSWORD=$(/opt/zextras/common/sbin/slappasswd -s "${LDAP_ADMIN_PASSWORD}")

cat <<EOF > /tmp/replace_admin_password.ldif
dn: uid=zimbra,cn=admins,cn=zimbra
changetype: modify
replace: userPassword
userPassword: ${SSHA_ADMIN_PASSWORD}
EOF

/opt/zextras/common/bin/ldapmodify -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f /tmp/replace_admin_password.ldif

for f in /opt/zextras/ldap/custom-ldifs/*.ldif; do
  /opt/zextras/common/bin/ldapadd -D cn=config -w "${LDAP_ROOT_PASSWORD}" -H ldap://localhost:1389 -f "$f"
done