FROM carbonio/ce-single-rhel8:23.10.0

USER root

COPY artifacts/x86_64/*el8.x86_64.rpm /packages/
RUN yum --help
RUN yum install /packages/*.rpm -y --noautoremove

COPY docker/single-server/mailbox_health_check.sh /opt/zextras/
COPY docker/single-server/prepare_data.sh /opt/zextras/
COPY docker/single-server/entrypoint.sh /opt/zextras/

RUN chown -R zextras:zextras /opt/zextras/mailbox_health_check.sh
RUN chown -R zextras:zextras /opt/zextras/prepare_data.sh
RUN chown -R zextras:zextras /opt/zextras/entrypoint.sh