# SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
# SPDX-License-Identifier: GPL-2.0-only

# Carbonio Common Appserver Conf resources
# See tmpfiles.d(5) for format

z /opt/zextras/conf/localconfig.xml 0640 zextras zextras
