<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Carbonio SOAP API Reference ${build.version}
</title>

<link rel="stylesheet" href="../pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../stylesheet.css" TITLE="Style">

<meta name="viewport" content="width=device-width, initial-scale=1">

<script type="text/javascript">
function windowTitle()
{
    parent.document.title="Command <${command.requestName}> (Carbonio SOAP API Reference ${build.version})";
}
</script>

</head>

<body onload="windowTitle();">

<table class="pure-table no-border-table overview-nav-top" cellspacing="3" cellpadding="0" border="0" summary=""  >
  <tbody>
  <tr valign="top" align="center">
  <td   class="NavBarCell1"><a href="../overview-summary.html"><b>Overview</b></a></td>
  <td   class="NavBarCell1"><a href="./service-summary.html"><b>Service</b></a></td>
  <td   class="NavBarCell1Rev"><b>Command</b></td>
  </tr>
  </tbody>
</table>

<div style="margin-top: 62px;">
    <h2>
        <a href="./service-summary.html">Service: ${service.name}</a>
    </h2>
</div>

<div class="command-intro">
    <div class="namespace">
    <b>Command:</b> ${command.name}
    <br>
    <b>Namespace:</b> ${command.namespace}
    <br>
    <b>Description:</b> ${command.description}
    </div>

    <div style="padding: 10px 0px 8px 0px; font-weight: bold;">Properties:</div>

    <table class="pure-table pure-table-bordered" cellspacing="0" cellpadding="5" border="1">
    <#if command.isNetworkEdition()>
        <tr> <td> Network edition only API </td> <td> <b>true</b> </td> </tr>
    </#if>
        <tr> <td> Authorization token required </td> <td> <b>${command.authRequiredDescription}</b> </td> </tr>
        <tr> <td> Admin Authorization token required </td> <td> <b>${command.adminAuthRequiredDescription}</b> </td> </tr>
    <#if command.hasDeprecationDescription()>
        <tr> <td> Deprecation information </td> <td> <b>${command.deprecation}</b> </td> </tr>
    </#if>
    </table>
</div>

<h2><a name="request">${command.requestName}</a></h2>
<#if command.request.description != "">
<p>
${command.request.description}
</p>
</#if>
<p class="code">
${command.request.htmlDescription}
</p>
<#if command.request.childDocumentableXmlUnits?size != 0>
<p>
elements and attributes you can define within a
<code>&lt;${command.requestName}&gt;</code> element:
</p>
<table class="pure-table pure-table-bordered pure-table-striped" cellspacing="0" cellpadding="5" border="1" width="100%">
<tbody>
    <tr   CLASS="TableHeadingColor">
        <td width="1%" nowrap><b>XPath</b></td>
        <td width="1%" nowrap><b>Required / Optional</b></td>
        <td><b>Description</b></td>
    </tr>
<#list command.request.childDocumentableXmlUnits as unit>
    <tr>
        <td> ${unit.tableKeyColumnContents} </td>
        <td>
        <#switch unit.occurrence>
              <#case "REQUIRED">
              Required (only 1)
              <#break>
              <#case "OPTIONAL">
              Optional (0 or 1)
              <#break>
              <#case "REQUIRED_MORE">
              Required (1 or more)
              <#break>
              <#case "OPTIONAL_MORE">
              Optional (0 or more)
              <#break>
        </#switch>
        </td>
        <td>${unit.descriptionForTable}</td>
    </tr>
</#list>
</tbody>
</table>
</#if>

<h2><a name="response">${command.responseName}</a></h2>
<#if command.response.description != "">
<p>
${command.response.description}
</p>
</#if>
<p class="code">
${command.response.htmlDescription}
</p>
<#if command.response.childDocumentableXmlUnits?size != 0>
<p>
elements and attributes you can define within a
<code>&lt;${command.responseName}&gt;</code> element:
</p>
<table class="pure-table pure-table-bordered pure-table-striped" cellspacing="0" cellpadding="5" border="1" width="100%">
<tbody>
    <tr   CLASS="TableHeadingColor">
        <td width="1%" nowrap><b>XPath</b></td>
        <td width="1%" nowrap><b>Required / Optional</b></td>
        <td><b>Description</b></td>
    </tr>
<#list command.response.childDocumentableXmlUnits as unit>
    <tr>
        <td> ${unit.tableKeyColumnContents} </td>
        <td>
        <#switch unit.occurrence>
              <#case "REQUIRED">
              Required (only 1)
              <#break>
              <#case "OPTIONAL">
              Optional (0 or 1)
              <#break>
              <#case "REQUIRED_MORE">
              Required (1 or more)
              <#break>
              <#case "OPTIONAL_MORE">
              Optional (0 or more)
              <#break>
        </#switch>
        </td>
        <td>${unit.descriptionForTable}</td>
    </tr>
</#list>
</tbody>
</table>
</#if>

<#-- start footer-->
<div class="last-element">&nbsp</div>
<div class="footer">
&copy Copyright <span id="year"></span>, The Zextras Team. All rights reserved.
</div>
<script>
  document.getElementById("year").innerHTML = new Date().getFullYear();
</script>
<#-- end footer-->

</body>
</html>
