<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
    <!-- Generated by ${build.version} on ${build.date} -->
    <TITLE> ${service.name} (Carbonio SOAP API Reference ${build.version}) </TITLE>
    <link rel="stylesheet" href="../pure-min.css" integrity="sha384-X38yfunGUhNzHpBaEBsWLO+A0HDYOQi8ufWDkZ0k9e0eXz/tH3II7uKZ9msv++Ls" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <LINK REL="stylesheet" TYPE="text/css" HREF="../stylesheet.css" TITLE="Style">
</HEAD>
<BODY class="service-frame-body">
    <div CLASS="all-commands-heading">
    <b>Service: </b>
    <A HREF="./service-summary.html" target="commandFrame">${service.name}</A>
    </div>
    <TABLE class="pure-table no-border-table" WIDTH="100%" SUMMARY="">
    <TR>
        <TD NOWRAP>
        <div class="FrameCommandHeadingFont"><br>Commands:</div>
        <FONT CLASS="FrameCommandItemFont">
            <#list service.commands as command>
            <A HREF="${command.name}.html" title="command in ${command.service.name}" target="commandFrame">${command.name}</A>
            <br>
            </#list>
        </FONT>
        </TD>
    </TR>
    </TABLE>
</BODY>
</HTML>
