// SPDX-FileCopyrightText: 2022 Synacor, Inc.
// SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: GPL-2.0-only

/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package com.zimbra.cs.index.query.parser;

public interface ParserTreeConstants
{
  int JJTROOT = 0;
  int JJTQUERY = 1;
  int JJTCLAUSE = 2;
  int JJTDEFAULTCLAUSE = 3;
  int JJTTEXTCLAUSE = 4;
  int JJTITEMCLAUSE = 5;
  int JJTDATECLAUSE = 6;
  int JJTVOID = 7;
  int JJTCONJUNCTION = 8;
  int JJTMODIFIER = 9;
  int JJTDATEMODIFIER = 10;
  int JJTSORTBY = 11;
  int JJTTEXTTERM = 12;
  int JJTITEMTERM = 13;
  int JJTDATETERM = 14;


  String[] jjtNodeName = {
    "Root",
    "Query",
    "Clause",
    "DefaultClause",
    "TextClause",
    "ItemClause",
    "DateClause",
    "void",
    "Conjunction",
    "Modifier",
    "DateModifier",
    "SortBy",
    "TextTerm",
    "ItemTerm",
    "DateTerm",
  };
}
/* JavaCC - OriginalChecksum=948171b49488e41742c8291039f25b7c (do not edit this line) */
