package com.zimbra.cs.account.commands;

import com.zimbra.cs.account.Command;
import com.zimbra.cs.account.CommandHandler;
import com.zimbra.cs.account.ProvUtil;

import java.util.HashMap;
import java.util.Map;

public class ProvUtilCommandHandlersFactory {
  public static Map<Command, CommandHandler> getCommandHandlersMap(ProvUtil provUtil) {
    var map = new HashMap<Command, CommandHandler>();
    var dumper = new ProvUtilDumper(provUtil.getConsole(), provUtil);
    map.put(Command.ADD_ACCOUNT_ALIAS, new AddAccountAliasCommandHandler(provUtil));
    map.put(Command.ADD_ACCOUNT_LOGGER, new AddAccountLoggerCommandHandler(provUtil));
    map.put(Command.ADD_DISTRIBUTION_LIST_ALIAS, new AddDistributionListAliasCommandHandler(provUtil));
    map.put(Command.ADD_DISTRIBUTION_LIST_MEMBER, new AddDistributionListMemberCommandHandler(provUtil));
    map.put(Command.AUTO_COMPLETE_GAL, new AutoCompleteGalCommandHandler(provUtil, dumper));
    map.put(Command.AUTO_PROV_CONTROL, new AutoProvControlCommandHandler(provUtil));
    map.put(Command.CHANGE_PRIMARY_EMAIL, new ChangePrimaryEmailCommandHandler(provUtil));
    map.put(Command.CHECK_PASSWORD_STRENGTH, new CheckPasswordStrengthCommandHandler(provUtil));
    map.put(Command.CHECK_RIGHT, new CheckRightCommandHandler(provUtil));
    map.put(Command.COMPACT_INBOX_MAILBOX, new CompactIndexMailboxCommandHandler(provUtil));
    map.put(Command.COPY_COS, new CopyCosCommandHandler(provUtil));
    map.put(Command.COUNT_ACCOUNT, new CountAccountCommandHandler(provUtil));
    map.put(Command.COUNT_OBJECTS, new CountObjectsCommandHandler(provUtil));
    map.put(Command.CREATE_ACCOUNT, new CreateAccountCommandHandler(provUtil));
    map.put(Command.CREATE_ALIAS_DOMAIN, new CreateAliasDomainCommandHandler(provUtil));
    map.put(Command.CREATE_BULK_ACCOUNTS, new CreateBulkAccountsCommandHandler(provUtil));
    map.put(Command.CREATE_CALENDAR_RESOURCE, new CreateCalendarResourceCommandHandler(provUtil));
    map.put(Command.CREATE_COS, new CreateCosCommandHandler(provUtil));
    map.put(Command.CREATE_DATA_SOURCE, new CreateDataSourceCommandHandler(provUtil));
    map.put(Command.CREATE_DISTRIBUTION_LIST, new CreateDistributionListCommandHandler(provUtil));
    map.put(Command.CREATE_DISTRIBUTION_LISTS_BULK, new CreateDistributionListsBulkCommandHandler(provUtil));
    map.put(Command.CREATE_DOMAIN, new CreateDomainCommandHandler(provUtil));
    map.put(Command.CREATE_DYNAMIC_DISTRIBUTION_LIST, new CreateDynamicDistributionListCommandHandler(provUtil));
    map.put(Command.CREATE_IDENTITY, new CreateIdentityCommandHandler(provUtil));
    map.put(Command.CREATE_SERVER, new CreateServerCommandHandler(provUtil));
    map.put(Command.CREATE_SIGNATURE, new CreateSignatureCommandHandler(provUtil));
    map.put(Command.CREATE_XMPP_COMPONENT, new CreateXMPPComponentCommandHandler(provUtil));
    map.put(Command.DELETE_ACCOUNT, new DeleteAccountCommandHandler(provUtil));
    map.put(Command.DELETE_CALENDAR_RESOURCE, new DeleteCalendarResourceCommandHandler(provUtil));
    map.put(Command.DELETE_COS, new DeleteCosCommandHandler(provUtil));
    map.put(Command.DELETE_DATA_SOURCE, new DeleteDataSourceCommandHandler(provUtil));
    map.put(Command.DELETE_DISTRIBUTION_LIST, new DeleteDistributionListCommandHandler(provUtil));
    map.put(Command.DELETE_DOMAIN, new DeleteDomainCommandHandler(provUtil));
    map.put(Command.DELETE_IDENTITY, new DeleteIdentityCommandHandler(provUtil));
    map.put(Command.DELETE_SERVER, new DeleteServerCommandHandler(provUtil));
    map.put(Command.DELETE_SIGNATURE, new DeleteSignatureCommandHandler(provUtil));
    map.put(Command.DELETE_XMPP_COMPONENT, new DeleteXMPPComponentCommandHandler(provUtil));
    map.put(Command.DESCRIBE, new DescribeCommandHandler(provUtil));
    map.put(Command.EXIT, new ExitCommandHandler(provUtil));
    map.put(Command.FLUSH_CACHE, new FlushCacheCommandHandler(provUtil));
    map.put(Command.GENERATE_DOMAIN_PRE_AUTH, new GenerateDomainPreAuthCommandHandler(provUtil));
    map.put(Command.GENERATE_DOMAIN_PRE_AUTH_KEY, new GenerateDomainPreAuthKeyCommandHandler(provUtil));
    map.put(Command.GET_ACCOUNT, new GetAccountCommandHandler(provUtil, dumper));
    map.put(Command.GET_ACCOUNT_LOGGERS, new GetAccountLoggersCommandHandler(provUtil));
    map.put(Command.GET_ACCOUNT_MEMBERSHIP, new GetAccountMembershipCommandHandler(provUtil));
    map.put(Command.GET_ALL_ACCOUNTS, new GetAllAccountsCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_ACCOUNT_LOGGERS, new GetAllAccountLoggersCommandHandler(provUtil));
    map.put(Command.GET_ALL_ADMIN_ACCOUNTS, new GetAllAdminAccountsCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_CALENDAR_RESOURCES, new GetAllCalendarResourcesCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_CONFIG, new GetAllConfigCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_COS, new GetAllCosCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_DISTRIBUTION_LISTS, new GetAllDistributionListsCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_DOMAINS, new GetAllDomainsCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_EFFECTIVE_RIGHTS, new GetAllEffectiveRightsCommandHandler(provUtil));
    map.put(Command.GET_ALL_FREEBUSY_PROVIDERS, new GetAllFbpCommandHandler(provUtil));
    map.put(Command.GET_ALL_MEMCACHED_SERVERS, new GetAllMemcachedServersCommandHandler(provUtil));
    map.put(Command.GET_ALL_MTA_AUTH_URLS, new GetAllMtaAuthURLsCommandHandler(provUtil));
    map.put(Command.GET_ALL_REVERSE_PROXY_BACKENDS, new GetAllReverseProxyBackendsCommandHandler(provUtil));
    map.put(Command.GET_ALL_REVERSE_PROXY_DOMAINS, new GetAllReverseProxyDomainsCommandHandler(provUtil));
    map.put(Command.GET_ALL_REVERSE_PROXY_URLS, new GetAllReverseProxyURLsCommandHandler(provUtil));
    map.put(Command.GET_ALL_RIGHTS, new GetAllRightsCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_SERVERS, new GetAllServersCommandHandler(provUtil, dumper));
    map.put(Command.GET_ALL_XMPP_COMPONENTS, new GetAllXMPPComponentsCommandHandler(provUtil, dumper));
    map.put(Command.GET_AUTH_TOKEN_INFO, new GetAuthTokenInfoCommandHandler(provUtil));
    map.put(Command.GET_CALENDAR_RESOURCE, new GetCalendarResourceCommandHandler(provUtil, dumper));
    map.put(Command.GET_CONFIG, new GetConfigCommandHandler(provUtil, dumper));
    map.put(Command.GET_COS, new GetCosCommandHandler(provUtil, dumper));
    map.put(Command.GET_CREATE_OBJECT_ATTRS, new GetCreateObjectAttrsCommandHandler(provUtil));
    map.put(Command.GET_DATA_SOURCES, new GetDataSourcesCommandHandler(provUtil, dumper));
    map.put(Command.GET_DISTRIBUTION_LIST, new GetDistributionListCommandHandler(provUtil, dumper));
    map.put(Command.GET_DISTRIBUTION_LIST_MEMBERSHIP, new GetDistributionListMembershipCommandHandler(provUtil));
    map.put(Command.GET_DOMAIN, new GetDomainCommandHandler(provUtil, dumper));
    map.put(Command.GET_DOMAIN_INFO, new GetDomainInfoCommandHandler(provUtil, dumper));
    map.put(Command.GET_EFFECTIVE_RIGHTS, new GetEffectiveRightsCommandHandler(provUtil));
    map.put(Command.GET_FREEBUSY_QUEUE_INFO, new GetFreebusyQueueInfoCommandHandler(provUtil));
    map.put(Command.GET_GRANTS, new GetGrantsCommandHandler(provUtil));
    map.put(Command.GET_IDENTITIES, new GetIdentitiesCommandHandler(provUtil, dumper));
    map.put(Command.GET_INDEX_STATS, new GetIndexStatsCommandHandler(provUtil));
    map.put(Command.GET_MAILBOX_INFO, new GetMailboxInfoCommandHandler(provUtil));
    map.put(Command.GET_MEMCACHED_CLIENT_CONFIG, new GetMemcachedClientConfigCommandHandler(provUtil));
    map.put(Command.GET_QUOTA_USAGE, new GetQuotaUsageCommandHandler(provUtil));
    map.put(Command.GET_RIGHT, new GetRightCommandHandler(provUtil, dumper));
    map.put(Command.GET_RIGHTS_DOC, new GetRightsDocCommandHandler(provUtil));
    map.put(Command.GET_SERVER, new GetServerCommandHandler(provUtil, dumper));
    map.put(Command.GET_SHARE_INFO, new GetShareInfoCommandHandler(provUtil));
    map.put(Command.GET_SIGNATURES, new GetSignaturesCommandHandler(provUtil, dumper));
    map.put(Command.GET_SPNEGO_DOMAIN, new GetSpnegoDomainCommandHandler(provUtil));
    map.put(Command.GET_XMPP_COMPONENT, new GetXMPPComponentCommandHandler(provUtil, dumper));
    map.put(Command.GRANT_RIGHT, new GrantRightCommandHandler(provUtil));
    map.put(Command.HELP, new HelpCommandHandler(provUtil));
    map.put(Command.LDAP, new LdapCommandHandler(provUtil));
    map.put(Command.MODIFY_ACCOUNT, new ModifyAccountCommandHandler(provUtil));
    map.put(Command.MODIFY_CALENDAR_RESOURCE, new ModifyCalendarResourceCommandHandler(provUtil));
    map.put(Command.MODIFY_CONFIG, new ModifyConfigCommandHandler(provUtil));
    map.put(Command.MODIFY_COS, new ModifyCosCommandHandler(provUtil));
    map.put(Command.MODIFY_DATA_SOURCE, new ModifyDataSourceCommandHandler(provUtil));
    map.put(Command.MODIFY_DISTRIBUTION_LIST, new ModifyDistributionListCommandHandler(provUtil));
    map.put(Command.MODIFY_DOMAIN, new ModifyDomainCommandHandler(provUtil));
    map.put(Command.MODIFY_IDENTITY, new ModifyIdentityCommandHandler(provUtil));
    map.put(Command.MODIFY_SERVER, new ModifyServerCommandHandler(provUtil));
    map.put(Command.MODIFY_SIGNATURE, new ModifySignatureCommandHandler(provUtil));
//    map.put(Command.MODIFY_XMPP_COMPONENT, new ModifyXMPPComponentCommandHandler(provUtil));
    map.put(Command.PURGE_ACCOUNT_CALENDAR_CACHE, new PurgeAccountCalendarCacheCommandHandler(provUtil));
    map.put(Command.PURGE_FREEBUSY_QUEUE, new PurgeFreebusyQueueCommandHandler());
    map.put(Command.PUSH_FREEBUSY, new PushFreebusyCommandHandler(provUtil));
    map.put(Command.PUSH_FREEBUSY_DOMAIN, new PushFreebusyDomainCommandHandler(provUtil));
    map.put(Command.RECALCULATE_MAILBOX_COUNTS, new RecalculateMailboxCountsCommandHandler(provUtil));
    map.put(Command.REINDEX_MAILBOX, new ReIndexMailboxCommandHandler(provUtil));
    map.put(Command.RELOAD_MEMCACHED_CLIENT_CONFIG, new ReloadMemcachedClientConfigCommandHandler(provUtil));
    map.put(Command.REMOVE_ACCOUNT_ALIAS, new RemoveAccountAliasCommandHandler(provUtil));
    map.put(Command.REMOVE_ACCOUNT_LOGGER, new RemoveAccountLoggerCommandHandler(provUtil));
    map.put(Command.REMOVE_DISTRIBUTION_LIST_ALIAS, new RemoveDistributionListAliasCommandHandler(provUtil));
    map.put(Command.REMOVE_DISTRIBUTION_LIST_MEMBER, new RemoveDistributionListMemberCommandHandler(provUtil));
    map.put(Command.RENAME_ACCOUNT, new RenameAccountCommandHandler(provUtil));
    map.put(Command.RENAME_CALENDAR_RESOURCE, new RenameCalendarResourceCommandHandler(provUtil));
    map.put(Command.RENAME_COS, new RenameCosCommandHandler(provUtil));
    map.put(Command.RENAME_DISTRIBUTION_LIST, new RenameDistributionListCommandHandler(provUtil));
    map.put(Command.RENAME_DOMAIN, new RenameDomainCommandHandler(provUtil));
    map.put(Command.RESET_ALL_LOGGERS, new ResetAllLoggersCommandHandler(provUtil));
    map.put(Command.REVOKE_RIGHT, new RevokeRightCommandHandler(provUtil));
    map.put(Command.SEARCH_ACCOUNTS, new SearchAccountsCommandHandler(provUtil, dumper));
    map.put(Command.SEARCH_CALENDAR_RESOURCES, new SearchCalendarResourcesCommandHandler(provUtil, dumper));
    map.put(Command.SEARCH_GAL, new SearchGalCommandHandler(provUtil, dumper));
    map.put(Command.SELECT_MAILBOX, new SelectMailboxCommandHandler(provUtil));
    map.put(Command.SET_ACCOUNT_COS, new SetAccountCosCommandHandler(provUtil));
    map.put(Command.SET_PASSWORD, new SetPasswordCommandHandler(provUtil));
    map.put(Command.SOAP, new SoapCommandHandler(provUtil));
    map.put(Command.SYNC_GAL, new SyncGalCommandHandler(provUtil, dumper));
    map.put(Command.UNLOCK_MAILBOX, new UnlockMailboxCommandHandler(provUtil));
    map.put(Command.VERIFY_INDEX, new VerifyIndexCommandHandler(provUtil));
    return map;
  }
}
