<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>

<!-- Generated by ${build.version} on ${build.date} -->
<TITLE>
All Commands (Zimbra SOAP API Reference ${build.version})
</TITLE>


</HEAD>

<BODY BGCOLOR="white">
<FONT size="+1" CLASS="FrameHeadingFont">
<B>All Commands</B></FONT>
<BR>

<TABLE BORDER="0" WIDTH="100%" SUMMARY="">
<TR>
<TD NOWRAP>
<FONT CLASS="FrameItemFont">
<#list allcommands as command>
<A HREF="./${command.service.name}/${command.name}.html" title="command in ${command.service.name}" target="commandFrame">${command.name}</A>
<BR>
</#list>
</FONT>
</TD>
</TR>
</TABLE>

</BODY>
</HTML>
