<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>

<!-- Generated by ${build.version} on ${build.date} -->
<TITLE>
All Commands (Carbonio SOAP API Reference ${build.version})
</TITLE>

 

<meta name="viewport" content="width=device-width, initial-scale=1">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../api-reference/stylesheet.css" TITLE="Style">

</HEAD>

<body class="all-commands-body">

<div class="FrameHeadingFont">
    <div class="all-commands-heading"><b>All Commands</b></div>
</div>

<table class="pure-table no-border-table" WIDTH="100%" SUMMARY="">
    <tr>
        <td NOWRAP>
            <div CLASS="FrameItemFont">
                <#list allcommands as command>
                <a HREF="./${command.service.name}/${command.name}.html" title="command in ${command.service.name}" target="commandFrame">${command.name}</a>
                <br>
                </#list>
            </div>
        </td>
    </tr>
</table>

</body>
</HTML>
