<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<HTML>
<HEAD>

<!-- Generated by ${build.version} on ${build.date} -->
<TITLE>
Carbonio SOAP API Reference ${build.version}
</TITLE>
 
<meta name="viewport" content="width=device-width, initial-scale=1">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../api-reference/stylesheet.css" TITLE="Style">
<SCRIPT type="text/javascript">
   targetPage = "" + window.location.search;
   if (targetPage != "" && targetPage != "undefined")
      targetPage = targetPage.substring(1);
   if (targetPage.indexOf(":") != -1)
      targetPage = "undefined";
   function loadFrames() {
      if (targetPage != "" && targetPage != "undefined")
	  top.classFrame.location = top.targetPage;
     }
</SCRIPT>
</HEAD>
<FRAMESET cols="22%,78%" title="" onLoad="top.loadFrames()">
<FRAMESET rows="42%,58%" title="" onLoad="top.loadFrames()">
<FRAME src="overview-frame.html" name="serviceListFrame" title="All Commands">

<FRAME src="allcommands-frame.html" name="serviceFrame" title="All Commands">
</FRAMESET>
<FRAME src="overview-summary.html" name="commandFrame" title="Service and command descriptions" scrolling="yes">
<NOFRAMES>
<BODY>
<H2>Frame Alert</H2>

<P>
This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client.
<BR>
</BODY>
</NOFRAMES>
</FRAMESET>
</HTML>
