<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Overview (Carbonio SOAP API Reference ${build.version})
</title>

 

<meta name="viewport" content="width=device-width, initial-scale=1">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../api-reference/stylesheet.css" TITLE="Style">

</head>

<body class="overview-frame-body" >

<table class="pure-table no-border-table" border="0" width="100%" summary="">
    <tr>
        <th align="left" nowrap>
        <span style="font-weight: bold;">Carbonio-CE SOAP API Reference</span>
        <br>
        <span style="font-size: small;">${build.version}</span>
        </th>
    </tr>
</table>

<table class="pure-table no-border-table" border="0" width="100%" summary="">
    <tr>
        <td nowrap><font class="FrameItemFont"><a href="allcommands-frame.html" target="serviceFrame">All Commands</a></font>
        <br>
        <br>
        <div class="FrameHeadingFont">Services:</div>

        <#list root.services as service>
        <font class="FrameItemFont"><a href="./${service.name}/service-frame.html" target="serviceFrame">${service.name}</a></font>
        <br>
        </#list>
        </td>
    </tr>
</table>

</body>
</html>
