<#--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Carbonio SOAP API Reference ${build.version}
</title>

<script type="text/javascript">
function windowTitle()
{
    parent.document.title="Zimbra SOAP API Reference ${build.version}";
}
</script>



<meta name="viewport" content="width=device-width, initial-scale=1">

<LINK REL ="stylesheet" TYPE="text/css" HREF="../api-reference/stylesheet.css" TITLE="Style">

</head>

<body  onload="windowTitle();">

<table class="pure-table no-border-table overview-nav-top" cellspacing="3" cellpadding="0" border="0" summary="">
  <tbody>
  <tr valign="top" align="center">
  <td><b>Overview</b></td>
  <td>Service</td>
  <td>Command</td>
  </tr>
  </tbody>
</table>

<div style="margin-top: 62px;">
  <h2>
    Carbonio SOAP API Reference ${build.version}
  </h2>
</div>
This document is the reference specification for the Carbonio SOAP API.

<p>
<TABLE class="pure-table pure-table-bordered pure-table-striped WIDTH="100%" CELLPADDING="3" CELLSPACING="0" SUMMARY="">
<TR CLASS="TableHeadingColor" >
  <td nowrap><b>SOAP API Services</b></td>
  <td nowrap><b>Services description</b></td>
</TR>
<#list root.services as service>
<TR >
<TD WIDTH="20%"><B><A HREF="./${service.name}/service-summary.html">${service.name}</A></B></TD>
<TD>${service.description}</TD>
</TR>
</#list>
</TABLE>

<#-- start footer-->
<div class="last-element">&nbsp</div>
<div class="footer">
&copy Copyright <span id="year"></span>, The Zextras Team. All rights reserved.
</div>
<script>
  document.getElementById("year").innerHTML = new Date().getFullYear();
</script>
<#-- end footer-->

</body>
</html>
