services:
  proxy:
    depends_on:
      - ldap
    entrypoint: "/scripts/entrypoint-proxy.sh carbonio-ce-directory-server.carbonio-system.svc.cluster.local:389"
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: nc -z localhost 443 || exit 1
      timeout: 10s
    hostname: carbonio-ce-proxy.carbonio-system.svc.cluster.local
    image: docker.io/carbonio/ce-proxy-u20:${DOCKER_IMAGES_VERSION}
    tty: true
    ports:
      - 110:110
      - 443:443
      - 6071:6071
    user: root
    volumes:
      - ./scripts/:/scripts/

  ldap:
    image: carbonio/ce-directory-server-u20:${DOCKER_IMAGES_VERSION}
    hostname: carbonio-ce-directory-server.carbonio-system.svc.cluster.local
    ports:
      - "389:389"
      - "8500:8500"
    healthcheck:
      test: netstat -ltn | grep -c :389
      retries: 20
    entrypoint: "/scripts/entrypoint-ldap.sh"
    tty: true
    user: root
    volumes:
      - ./scripts/:/scripts/
  mailbox:
    image: carbonio/ce-appserver-u20:${DOCKER_IMAGES_VERSION}
    entrypoint: "/scripts/entrypoint-mailbox.sh carbonio-ce-directory-server.carbonio-system.svc.cluster.local:389"
    hostname: carbonio-ce-appserver.carbonio-system.svc.cluster.local
    ports:
      - "5005:5005"
    depends_on:
      - ldap
    tty: true
    healthcheck:
      interval: 60s
      retries: 10
      start_period: 20s
      test: nc -z localhost 7071 || exit 1
      timeout: 10s
    volumes:
      - ./scripts/:/scripts/
      - ./../../store/target/zm-store-jar-with-dependencies.jar:/scripts/zm-store-jar-with-dependencies.jar
    user: root

